/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2015-12-09 11:38:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005flogin_005fconfirm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");

	String user_id=request.getParameter("user_id"); //유저의 이름
	String films_id=request.getParameter("films_id");
	//int films_id2=Integer.parseInt(films_id); //선택한 영화의 id
	
	System.out.println(user_id);
	//System.out.println(films_id2);
	

      out.write("\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<h2>회원정보 변경</h2>\n");
      out.write("\t<form method =\"post\" action=\"membership_control.jsp\" name=\"form1\">\n");
      out.write("\t<input type=hidden name=\"action\" value=\"change\">\n");
      out.write("\t<input type=hidden name=\"user_id\" value=");
      out.print(user_id);
      out.write(">\n");
      out.write("\t<input type=hidden name=\"films_id\" value=");
      out.print(films_id );
      out.write(">\n");
      out.write("\t<table width=\"250\" border=\"1\"align=\"center\" cellspacing=\"0\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcellpadding=\"5\">\n");
      out.write("\t\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>ID</td>\n");
      out.write("\t\t<td><input type=\"text\" name=\"name_mem\" value=");
      out.print(user_id);
      out.write(" disabled=disabled size=10></td>\n");
      out.write("\t</tr>\n");
      out.write("\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>비밀번호</td>\n");
      out.write("\t\t<td><input type=\"password\" name=\"password\" size=10></td>\n");
      out.write("\t</tr>\n");
      out.write("\t\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>비밀번호 확인</td>\n");
      out.write("\t\t<td><input type=\"password\" name=\"password_confirm\" size=10></td>\n");
      out.write("\t</tr>\n");
      out.write("\t\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>나이</td>\n");
      out.write("\t\t<td><input type=\"password\" name=\"age_mem\" size=10></td>\n");
      out.write("\t</tr>\n");
      out.write("\t\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td><input type=\"Submit\" name=\"login_button\" value=\"승인\" size=1>\n");
      out.write("\t\t\t<input type=\"reset\" name=\"initialization_button\" value=\"초기화\" size=1>\n");
      out.write("\t\t</td>\n");
      out.write("\t</tr>\n");
      out.write("</table>\n");
      out.write("</form>\n");
      out.write("<hr><hr>\n");
      out.write("\n");
      out.write("<h2>회원정보 변경x</h2>\n");
      out.write("\t<form method =\"post\" action=\"membership_control.jsp\" name=\"form2\">\n");
      out.write("\t <input type=hidden name=\"action\" value=\"enter\"> \n");
      out.write("\t<input type=hidden name=\"user_id\" value=");
      out.print(user_id);
      out.write(">\n");
      out.write("\t<input type=hidden name=\"films_id\" value=");
      out.print(films_id );
      out.write(">\n");
      out.write("\t<table width=\"250\" border=\"1\"align=\"center\" cellspacing=\"0\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcellpadding=\"5\">\n");
      out.write("\t\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>변경 안하고 입장</td>\n");
      out.write("\t\n");
      out.write("\t</tr>\n");
      out.write("\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td><input type=\"Submit\" name=\"login_button\" value=\"입장\" size=1>\n");
      out.write("\t\t</td>\n");
      out.write("\t</tr>\n");
      out.write("</table>\n");
      out.write("</form>\n");
      out.write("<hr><hr>\n");
      out.write("<h2>로그아웃</h2>\n");
      out.write("\t<form method =\"post\" action=\"membership_control.jsp\" name=\"form2\">\n");
      out.write("\t <input type=hidden name=\"action\" value=\"exit\"> \n");
      out.write("\t<input type=hidden name=\"user_id\" value=");
      out.print(user_id);
      out.write(">\n");
      out.write("\t<input type=hidden name=\"films_id\" value=");
      out.print(films_id );
      out.write(">\n");
      out.write("\t<table width=\"250\" border=\"1\"align=\"center\" cellspacing=\"0\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcellpadding=\"5\">\n");
      out.write("\t\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>로그아웃</td>\n");
      out.write("\t\n");
      out.write("\t</tr>\n");
      out.write("\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td><input type=\"Submit\" name=\"login_button\" value=\"로그아웃\" size=1>\n");
      out.write("\t\t</td>\n");
      out.write("\t</tr>\n");
      out.write("</table>\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
